version: "3.8"

secrets:
  config_json:
    file: secrets.json

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/ssl:/etc/nginx/certs
    networks:
      - foundry

  foundry:
    image: felddy/foundryvtt:latest
    build: .
    hostname: foundry.localhost
    init: true
    restart: "unless-stopped"
    depends_on:
      - nginx-proxy
    volumes:
      - type: bind
        source: ../foundrydata
        target: /data
    environment:
      - VIRTUAL_HOST=foundry.localhost
      - VIRTUAL_PORT=30000
    ports:
      - "30000"
    secrets:
      - source: config_json
        target: config.json
    networks:
      - foundry

networks:
  foundry:
